#!/bin/bash
sudo apt-get update
sudo apt-get -y install ruby
sudo apt-get -y install wget
cd /home/ubuntu
wget https://bucket-name.s3.region-identifier.amazonaws.com/latest/install
sudo chmod +x ./install
sudo ./install auto
sudo service codedeploy-agent start
